<?php
if (!defined('ABSPATH')) exit;

return [
    'type',
    'material',
    'glazing',
    'profile',
    'colorExterior',
    'colorInterior',
    'form',
    'sashes',
    'construction',
    'sunProtection',
    'shadingColor',
    'boxShape',
    'slatType',
    'insectProtection',
    'componentColors',
    'drive',
    'controlSide',
    'dimensions',
    'sprossen',
    'sprossenaufteilung',
    'extras',
    'ornamentGlass',
    'soundInsulationGlass',
    'spacer',
    'securityFitting',
    'handle',
    'guideRails',
    'windowsill',
    'existingShutterBox',
    'customerPhoto',
];
